"""Freeze author-assigned labels before inference; ambiguity is in neighboring purposes."""
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
cases=[
('demand_letter','settlement_release','Counsel writes: Our client will accept $19,500 to resolve the collision injury claim. Enclosed is proposed release wording for discussion: claimant releases all bodily injury claims upon receipt of agreed funds. That wording is a draft enclosure, not an executed agreement. Your insured disputes the treatment duration. Please respond to this offer within fourteen days; we can discuss revisions to the proposed terms. No payment has been received and our client has signed nothing. The immediate action sought is your settlement response.'),
('settlement_release','demand_letter','The parties previously exchanged a demand for $35,000 and a counteroffer for $18,000. They now agree to settle the collision bodily injury claim for $22,000. In consideration of that payment, claimant Rowan Vale releases driver Ellis Brook and the insurer from the identified injury claims. This agreement does not release the separately pending vehicle damage claim. Rowan Vale signed September 10; Ellis Brook signed September 11. Payment is due within ten days of receipt of this executed agreement. This text records the final agreed obligations.'),
('medical_bill','medical_record','River Clinic account 4401. Patient Taylor Moss, service June 4. Diagnosis recorded for billing: cervical strain after motor vehicle collision. The clinician documented tenderness and recommended a home exercise program. Office evaluation $180; therapeutic exercise $120; supplies $25. Total charges $325; insurer payment $100; adjustment $25; patient balance $200. Please remit the remaining balance within thirty days and include the account number. Clinical notes are included only to support the billed services. Billing office contact is listed below.'),
('medical_record','medical_bill','Follow-up visit, June 18. Patient Taylor Moss reports less neck pain but difficulty turning while driving. Examination: cervical rotation limited on the right; strength intact; no sensory loss. Assessment: resolving cervical strain. Plan: continue exercises, reduce visit frequency, reassess in two weeks. The patient asked about a $200 balance appearing in the portal; the therapist referred that question to billing and did not verify the amount. No charges or payment instructions are issued in this signed clinical encounter note.'),
('witness_statement','police_report','Recorded interview of Avery Lane by officer Bell. Bell: Tell me what you saw. Lane: I was waiting at the bus stop when the delivery van struck the parked car. I heard the impact and saw the driver step out. Bell: Did you see a traffic signal? Lane: No; I could not see the intersection. Bell: Did either driver speak to you? Lane: The van driver asked if I was injured. I was not. The foregoing is my account, read back and approved by me, Avery Lane. The officer certified the recording, without adding investigative findings.'),
('police_report','witness_statement','Officer Bell, collision investigation supplement. Witness Avery Lane stated, “I was waiting at the bus stop when the delivery van struck the parked car.” I inspected both vehicles, photographed the contact points, and measured debris placement. The van had damage consistent with the parked car’s rear corner. The driver denied seeing the car before impact. Based on my scene observations and the recorded statements, I documented an improper backing maneuver as the contributing action. Witness remarks above are quoted evidence within my investigation. Filed and signed by officer Bell.'),
('subrogation_notice','demand_letter','Counsel for Cedar Insurance requests reimbursement arising from the collision involving your insured. Cedar paid its policyholder $8,400 for vehicle repairs and seeks that payment plus the $500 deductible. Enclosed invoices support the loss. We demand $8,900 within thirty days and are willing to discuss a compromise and mutual release of this recovery claim. We do not represent an injured person or seek compensation for bodily injury. Payment records establish the amount already disbursed by Cedar; please direct your recovery response to counsel.'),
('other','demand_letter','Repair facility collection notice to vehicle owner. Your vehicle repair invoice is overdue. We demand payment of the $2,800 balance within ten days and may refer the account to collections. The insurer has already issued its payment directly to you. This letter seeks your payment of our existing invoice; it does not estimate future repairs, propose settlement of an injury claim, or request recovery of an insurer payment. Contact the facility accounts office to discuss a payment schedule.'),
]
rows=[dict(id=f'boundary_{i:02}',expected_label=gold,confusable_label=near,text=text) for i,(gold,near,text) in enumerate(cases,1)]
(ROOT/'data/boundary_documents.jsonl').write_text(''.join(json.dumps(r)+'\n' for r in rows))
(ROOT/'BOUNDARY_DOCUMENTS.md').write_text('# Complete synthetic boundary examples\n\nAuthor-assigned labels were frozen before inference. These are short purpose-discrimination tests, not realistic long claims packets. All content is fictional.\n\n'+'\n\n'.join(f"## {r['id']} — {r['expected_label']}\n\nNeighboring category: {r['confusable_label']}\n\n{r['text']}" for r in rows)+'\n')
print('Created',len(rows),'frozen boundary examples')
